### ISSUE TITLE
Depreciation Notices

### ISSUE THREAD

**Issue by cshenry13** [paulgibbs/Welcome-Pack#5]
I'm seeing the following notices from this plugin:

`Deprecated: Non-static method DP_Welcome_Pack_Admin::admin_page() should not be called statically in C:\xampp2020-2\htdocs\20200720_openinindiana\wp-includes\class-wp-hook.php on line 287

Deprecated: screen_icon is deprecated since version 3.8.0 with no alternative available. in C:\xampp2020-2\htdocs\20200720_openinindiana\wp-includes\functions.php on line 4869

Deprecated: get_screen_icon is deprecated since version 3.8.0 with no alternative available. in C:\xampp2020-2\htdocs\20200720_openinindiana\wp-includes\functions.php on line 4869`

**Comment by paulgibbs** [comment]
Hi - plugin hasn't been updated since 2014. Much of the functionality has been put into BuddyPress core itself over the years. I'll update the Github status of this project. :)
